{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.my_flutter",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 15580566,
          "sha512": "0a3e54820a1416c3aba65e644e105663958ac41b8aa296a24abaceaa62fabece736fdc4035daaa87f2553df61bcca6c8ac73205b28a0922aba3d32e67b48f0a7",
          "sha256": "a9f4f0eedaf8786a00ed3261bde9bcdfde9d71629b9236e7bbd7fe7131e0c86b",
          "sha1": "bffaa0999f815ef2445d462f120e54b9a1ea9055",
          "md5": "46fa368cc07b22961517e1457e3f13a2"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 15580566,
          "sha512": "0a3e54820a1416c3aba65e644e105663958ac41b8aa296a24abaceaa62fabece736fdc4035daaa87f2553df61bcca6c8ac73205b28a0922aba3d32e67b48f0a7",
          "sha256": "a9f4f0eedaf8786a00ed3261bde9bcdfde9d71629b9236e7bbd7fe7131e0c86b",
          "sha1": "bffaa0999f815ef2445d462f120e54b9a1ea9055",
          "md5": "46fa368cc07b22961517e1457e3f13a2"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.0-sources.jar",
          "url": "flutter_debug-1.0-sources.jar",
          "size": 1681,
          "sha512": "e88cc66e8de68fe38358726cc1129195a534a7e09d0fdda874faa3fd838ce1224ad2e009da488c0bc7218ec58cde7532cdcf07be876860b32d0eecf0974febdc",
          "sha256": "fcb7f445282ef2a878c90d846b321b768a0524d7a007651d35296bce7c049745",
          "sha1": "bc5e41a14362473b87e9b955f729a8069efa1c6f",
          "md5": "a8043220ac09ba2d691d51459b2778d3"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.0-javadoc.jar",
          "url": "flutter_debug-1.0-javadoc.jar",
          "size": 269297,
          "sha512": "9c9b65f12b802a07c6d8fdff230950ff653b6c144c7596c692aea59a591a1a917bd5bd7c9442254173e99c450248fb96598a8cad1aa42ef8c07a0747c77cfc87",
          "sha256": "06077a1566f0cd422ea4cd06ae1b0d9844959474d62d61084018a8fa834375e4",
          "sha1": "f0294b6ac536a7dc026c688aec3f88810d0e3cb5",
          "md5": "a4150d12f76d1996af9008c445d71976"
        }
      ]
    }
  ]
}
